### ISSUE TITLE
Problem Running  ZabbixMaintanance  Script

### ISSUE THREAD

**Issue by farhandiwan** [CheggEng/zabbix-scripts#1]
Running this script on Centos7. To add a   list of  hosts in Zabbix. Can you tell me where to find the module zabbix.api or suggest a fix for that.

Traceback (most recent call last):
  File "./zabbixMaintenance.py", line 6, in <module>
    from zabbix.api import ZabbixAPI
ImportError: No module named zabbix.api

**Comment by analogrithems** [comment]
In the readme you will see this script requires
```
sudo pip install py-zabbix
```
